name = "mypinkshop-backend-v2"
main = "src/index.js"
compatibility_date = "2024-12-18"

[[d1_databases]]
binding = "DB"
database_name = "mypinkshop-db"
database_id = "00343abb-2eb1-4010-84a5-f5608523de3d"

[vars]
FRONTEND_URL = "https://mypinkshop.com"
JWT_SECRET = "YbSNEP0omcxXSjCNQM6hCfnr0zwrpZhZElZgZdONQqI"
SENDER_API_KEY = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOWU0YzI3ODU5ZTNkNjgwNzlhMWZkNDQ4YTRlMDIxZjk2N2JlZjMzOTU1MzMzNGE5ZGJmMzg0MmVjMTJhYjk1NzI1ZDFhNWU2NThmZTZlZmYiLCJpYXQiOjE3ODEwMjk1OTAuNTg1NDY1LCJuYmYiOjE3ODEwMjk1OTAuNTg1NDY5LCJleHAiOjQ5MzQ2Mjk1OTAuNTgyODM3LCJzdWIiOiIxMDc4MTA4Iiwic2NvcGVzIjpbXX0.eweCPR5vhbzknP02jJ0_mSAEOzBjxeLR6EFqGjXvacbQ7swkVXnoM0QXsC8CTJB2DfPqIAa3L2V_87Ocqdjr7xmdpUEIZsKxNnDb4L2EcXl_b7WIE9w6Ux3J4y16tr-x6g_a2CTCGJ0PYQSKEfTHhloDXwpzfVqJhb62xUSWp4u8GwkG_YLb6cChH5xMk8QyfvUxelsDCVmFrlrAQ11fsMEwLGdU0PlG6Bx6TsD5uUANwey2y7ow3y_dArSx6AUZmvhvJvl0KsuM2QtazyUPf5UlZuCxCUmk1fj92AyQmX9RlnCPI1DzT058LEWP0OocAz-rwZhuurJCOGaFzD58kxXRSVwgzzHYGyMXwG5I65pw9Nu7Gdl-WXh8op8k6c7uR4UHwuzEZOjvuUSBd0hkzrFTNCHdAHKsMl9c6Q5DFA-HBfiE8pcNbDStRpb02JyJRVL4RHZOpxO_4m5K-60PW2WPh8EZiezEEynqi_H6ZhY0iw6n9ezurql8Pbh3uG-gbjKOcah0gZLHQdfmX2lZvYkIBQDhtpXCf0uSBH8ndr0wx71dEwTVWykPTTVHcxgrwqWjAdSLHkWoBxB0UDQP6AlriNeYTJipvdqPWOFmJl54VcArtNnGj_daQwBkPjLgSdTpg5IIiIM-8s-nztwvUPI73x07W7qnlLEKFJH88rc"
